/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OoO.Form.Home;

/**
 *
 * @author huy
 */
public class AddEggFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEggFrame
     */
    public AddEggFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        EReturnBtn = new javax.swing.JLabel();
        ENextBtn = new javax.swing.JLabel();
        EPreviousBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ETextArea = new javax.swing.JLabel();
        EBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        EReturnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/ReturnBtn.png"))); // NOI18N
        EReturnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EReturnBtnMouseClicked(evt);
            }
        });
        jPanel2.add(EReturnBtn);
        EReturnBtn.setBounds(0, 80, 64, 64);

        ENextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/NextButton.png"))); // NOI18N
        jPanel2.add(ENextBtn);
        ENextBtn.setBounds(735, 220, 64, 64);

        EPreviousBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/PreviousButton.png"))); // NOI18N
        jPanel2.add(EPreviousBtn);
        EPreviousBtn.setBounds(50, 220, 64, 64);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/AddBtn.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(740, 350, 82, 55);

        jScrollPane1.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(572, 94));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 140, 560, 270);

        ETextArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/GridView.png"))); // NOI18N
        jPanel2.add(ETextArea);
        ETextArea.setBounds(120, 120, 612, 323);

        EBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/AddEgg/AddEggTab.png"))); // NOI18N
        jPanel2.add(EBackGround);
        EBackGround.setBounds(0, 0, 853, 480);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 853, 480);

        setSize(new java.awt.Dimension(869, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EReturnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EReturnBtnMouseClicked
        Home Homef = new Home();
        this.dispose();
        Homef.setVisible(true);
    }//GEN-LAST:event_EReturnBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEggFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEggFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EBackGround;
    private javax.swing.JLabel ENextBtn;
    private javax.swing.JLabel EPreviousBtn;
    private javax.swing.JLabel EReturnBtn;
    private javax.swing.JLabel ETextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
