/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OoO.Form.Home;



/**
 *
 * @author huy
 */
public class BasketFrame extends javax.swing.JFrame {

    /**
     * Creates new form BasketFrame
     */
    public BasketFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReturnBtn = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        TextAreaImg = new javax.swing.JLabel();
        NextBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JLabel();
        EditBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ReturnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/ReturnBtn.png"))); // NOI18N
        ReturnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBtnMouseClicked(evt);
            }
        });
        jPanel1.add(ReturnBtn);
        ReturnBtn.setBounds(20, 125, 60, 60);

        ScrollPane.setBorder(null);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setBorder(null);
        ScrollPane.setViewportView(jTextArea);

        jPanel1.add(ScrollPane);
        ScrollPane.setBounds(240, 220, 767, 384);

        TextAreaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/GridView.png"))); // NOI18N
        jPanel1.add(TextAreaImg);
        TextAreaImg.setBounds(220, 200, 817, 431);

        NextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/NextButton.png"))); // NOI18N
        NextBtn.setToolTipText("");
        jPanel1.add(NextBtn);
        NextBtn.setBounds(1050, 350, 64, 64);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/PreviousButton.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 350, 64, 64);

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/save.png"))); // NOI18N
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        jPanel1.add(SaveBtn);
        SaveBtn.setBounds(1050, 540, 64, 64);

        EditBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/EditBtn.png"))); // NOI18N
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        jPanel1.add(EditBtn);
        EditBtn.setBounds(1050, 450, 64, 64);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OoO/img/Basket/BasketTab.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBtnMouseClicked
        
        Home Homef = new Home();
        this.dispose();
        Homef.setVisible(true);
    }//GEN-LAST:event_ReturnBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        jTextArea.setEditable(true);
    }//GEN-LAST:event_EditBtnMouseClicked

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel EditBtn;
    private javax.swing.JLabel NextBtn;
    private javax.swing.JLabel ReturnBtn;
    private javax.swing.JLabel SaveBtn;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel TextAreaImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
