/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.myComponent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javafx.scene.text.TextAlignment;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.text.html.CSS;

/**
 *
 * @author DAT
 */
public class ButtonWithImage extends javax.swing.JPanel {

    public String getText() {
        return Text;
    }

    public void setText(String Text) {
        this.Text = Text;
        this.lblText.setText(Text);
    }

    public Color getTextColor() {
        return TextColor;
    }

    public void setTextColor(Color TextColor) {
        this.TextColor = TextColor;
        this.lblText.setForeground(TextColor);
    }

    public Font getTextFont() {
        return TextFont;
    }

    public void setTextFont(Font TextFont) {
        this.TextFont = TextFont;
        this.lblText.setFont(TextFont);
    }

    public float getFontSize() {
        return FontSize;
    }

    public void setFontSize(float FontSize) {
        this.FontSize = FontSize;
        this.lblText.setFont(TextFont.deriveFont(FontSize));
    }

    public ImageIcon getImage() {
        return Image;
    }

    public void setImage(ImageIcon Image) {
        this.Image = Image;
        this.lblBackground.setIcon(Image);
    }

    public int getWidth() {
        return Width;
    }

    public void setWidth(int Width) {
        this.Width = Width;
        this.setWidth(Width);
    }

    String Text;
    Color TextColor;
    Font TextFont;
    float FontSize;
    ImageIcon Image;
    int Width;
    /**
     * Creates new form ButtonWithImage
     */
    public ButtonWithImage() {
        Text = "CLick me!!!";
        Width = 100;
        FontSize = 25;
        TextFont = Tools.FontTool.getFont(
                "Cambria",
                FontSize);
        Image = new ImageIcon(Tools.ImageTool.getScaledImage(
                        "Default\\ImageButton.png", 
                        Width, 
                        (int)FontSize * 2));
        initComponents();
        design();
    }

    public ButtonWithImage(
            String Text,
            Color TextColor,
            Font TextFont,
            ImageIcon Image
            ){
        this.Text = Text;
        this.TextColor = TextColor;
        this.TextFont = TextFont;
        this.FontSize = TextFont.getSize();
        this.Image = Image;
        this.Width = Image.getIconWidth();
        initComponents();
        design();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("Click me");
        lblText.setMaximumSize(new Dimension(this.getWidth(),this.getHeight()));
        lblText.setMinimumSize(new Dimension(this.getWidth(),this.getHeight()));
        lblText.setPreferredSize(new Dimension(this.getWidth(),this.getHeight()));
        add(lblText);
        lblText.setBounds(1, -4, 420, 60);
        add(lblBackground);
        lblBackground.setBounds(0, 0, 420, 60);
    }// </editor-fold>//GEN-END:initComponents
    
    private void design(){
        this.setBackground(new Color(0,0,0,0));
        this.setOpaque(false);
        
        lblBackground.setBackground(new Color(0,0,0,0));
        lblBackground.setBounds(
                0,
                0,
                this.Image.getIconWidth(),
                this.Image.getIconHeight());
        lblBackground.setIcon(Image);
        
        lblText.setSize(
                lblBackground.getWidth(),
                lblBackground.getHeight()
                );
        lblText.setLocation(
                (lblBackground.getWidth() - lblText.getWidth()) /2,
                (lblBackground.getHeight() - lblText.getHeight()) /2
                );
        lblText.setBackground(new Color(0,0,0,0));
        lblText.setText(Text);
        lblText.setFont(TextFont);
        lblText.setForeground(TextColor);
        lblText.setVerticalAlignment(SwingConstants.CENTER);
        lblText.setVerticalTextPosition(SwingConstants.CENTER);
        
        this.add(lblBackground);
        lblBackground.add(lblText);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
