/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.myComponent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author DAT
 */
public class myTextArea extends javax.swing.JPanel {

    private ImageIcon Icon;
    private ImageIcon FooterLine;
    private String TextHolder;
    private Color TextColor;
    private Font TextFont;

    public ImageIcon getIcon() {
        return Icon;
    }

    public void setIcon(ImageIcon Icon) {
        this.Icon = Icon;
    }

    public ImageIcon getFooterLine() {
        return FooterLine;
    }

    public void setFooterLine(ImageIcon FooterLine) {
        this.FooterLine = FooterLine;
    }

    public String getTextHolder() {
        return TextHolder;
    }

    public void setTextHolder(String TextHolder) {
        this.TextHolder = TextHolder;
    }

    public Color getTextColor() {
        return TextColor;
    }

    public void setTextColor(Color TextColor) {
        this.TextColor = TextColor;
    }

    public Font getTextFont() {
        return TextFont;
    }

    public void setTextFont(Font TextFont) {
        this.TextFont = TextFont;
    }

    /**
     * Creates new form myTextArea
     */
    private myTextArea() {
    }

    public myTextArea(
            String TextHolder,
            Color TextColor,
            Font TextFont,
            ImageIcon Icon,
            ImageIcon FooterLine) {
        this.Icon = Icon;
        this.FooterLine = FooterLine;
        this.TextHolder = TextHolder;
        this.TextColor = TextColor;
        this.TextFont = TextFont;
        initComponents();
        addAction();
    }

    private void addAction() {
        this.TextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                TextField_FocusGained(e);
            }
            
            @Override
            public void focusLost(FocusEvent e){
                TextField_Focuslost(e);
            }
        }
        );
    }
    
    private void TextField_FocusGained(FocusEvent e){
//        this.TextField.setForeground(TextColor);
        if(this.TextField.getText().equals(this.TextHolder)){
            this.TextField.setText("");
        }
    }
    
    private void TextField_Focuslost(FocusEvent e){
//        this.TextField.setForeground(new Color());
        if(this.TextField.getText().equals("")){
            this.TextField.setText(this.TextHolder);
        }
    }
    public String getText() {
        return this.TextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFooterLine = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();

        setBackground(new Color(0,0,0,0));
        setLayout(null);

        lblFooterLine.setBackground(new Color(0,0,0,0));
        lblFooterLine.setIcon(this.FooterLine);
        lblFooterLine.setMaximumSize(new Dimension(
            this.getWidth(),
            this.getHeight()/ 8));
    lblFooterLine.setMinimumSize(new Dimension(
        this.getWidth(),
        this.getHeight()/ 8));
lblFooterLine.setPreferredSize(new Dimension(
    this.getWidth(),
    this.getHeight()/ 8));
    add(lblFooterLine);
    lblFooterLine.setBounds(0, 60, 430, 16);

    lblIcon.setBackground(new Color(0,0,0,0));
    lblIcon.setIcon(this.Icon);
    lblIcon.setMaximumSize(new Dimension(
        this.getWidth() / 5,
        this.getHeight() * 4/ 5));
lblIcon.setMinimumSize(new Dimension(
    this.getWidth() / 5,
    this.getHeight() * 4/ 5));
    lblIcon.setPreferredSize(new Dimension(
        this.getWidth() / 5,
        this.getHeight() * 4/ 5));
add(lblIcon);
lblIcon.setBounds(4, 0, 63, 63);

TextField.setFont(this.TextFont);
TextField.setForeground(this.TextColor);
TextField.setText(this.TextHolder);
TextField.setBorder(null);
TextField.setDoubleBuffered(true);
TextField.setMaximumSize(new Dimension(
    this.getWidth() * 4 / 5,
    this.getHeight() * 4/ 5));
    TextField.setMinimumSize(new Dimension(
        this.getWidth() * 4 / 5,
        this.getHeight() * 4/ 5));
add(TextField);
TextField.setBounds(72, 0, 357, 63);
}// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel lblFooterLine;
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables
}
