/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.myComponent;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import javax.swing.ImageIcon;

/**
 *
 * @author DAT
 */
public class TitleWithIconLine extends javax.swing.JPanel {

    ImageIcon Line;
    ImageIcon Icon;
    String Text;
    Font TextFont;
    Color ForeColor;

    /**
     * Creates new form TitleWithIconLine
     */
    private TitleWithIconLine() {
    }

    public TitleWithIconLine(ImageIcon Line, ImageIcon Icon, String Text, Font TextFont, Color ForeColor) {
        this.Line = Line;
        this.Icon = Icon;
        this.Text = Text;
        this.TextFont = TextFont;
        this.ForeColor = ForeColor;
        initComponents();
        design();
    }

    private void design() {
        this.setPreferredSize(
                new Dimension(
                        Line.getIconWidth()
                        + Icon.getIconWidth(),
                        Icon.getIconHeight()
                ));
        this.setOpaque(false);
        this.setBackground(new Color(0, 0, 0, 0));

        /*
        * lblIcon
         */
        lblIcon.setIcon(Icon);
        lblIcon.setLocation(new Point(0, 0));
        lblIcon.setSize(
                Icon.getIconWidth(),
                Icon.getIconHeight());
        lblIcon.setBackground(new Color(00, 0, 0, 0));

        /*
        * lblLine
         */
        lblLine.setIcon(Line);
        lblLine.setLocation(
                new Point(
                        Icon.getIconWidth(),
                        Icon.getIconHeight() / 2
                        - Line.getIconHeight()
                ));
        lblLine.setSize(
                Line.getIconWidth(),
                Line.getIconHeight());
        lblLine.setBackground(new Color(00, 0, 0, 0));

        /*
        * lblTitle
         */
        lblTitle.setText(Text);
        lblTitle.setFont(TextFont);
        lblTitle.setForeground(ForeColor);
        lblTitle.setLocation(
                new Point(
                        Icon.getIconWidth(),
                        Icon.getIconHeight() / 2
                ));
        lblTitle.setSize(
                Line.getIconWidth(),
                Icon.getIconHeight() / 2
                - Line.getIconHeight()
        );
        lblTitle.setBackground(new Color(00, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLine = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLine, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTransparent(boolean chk) {
        if (chk) {
            lblIcon.setIcon(null);
            lblLine.setIcon(null);
            lblTitle.setForeground(ForeColor);
        } else {
            lblIcon.setIcon(Icon);
            lblLine.setIcon(Line);
            lblTitle.setForeground(new Color(0, 0, 0, 0));
        }
        lblIcon.repaint();
        lblLine.repaint();
        lblTitle.repaint();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
