/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OoO.Form.Component;

import OoO.Tools.ImageTool;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.OverlayLayout;

/**
 *
 * @author DAT
 */
public class pnlFrameHeader extends javax.swing.JPanel {

    /**
     * Creates new form pnlFrameHeader
     */
    public pnlFrameHeader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBtnCardLayout1 = new javax.swing.JLabel();
        lblImgFrameHeader = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        lblBtnCardLayout1.setBackground(new Color(0,0,0,0));
        lblBtnCardLayout1.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lblBtnCardLayout1.setForeground(new Color(255,255,255,255));
        lblBtnCardLayout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnCardLayout1.setIcon(new ImageIcon(ImageTool.getScaledImage("Home\\Component\\FrameHeader\\imgBtnCardLayout.png", 100, 50)));
        lblBtnCardLayout1.setText("jLabel1");
        lblBtnCardLayout1.setMaximumSize(new java.awt.Dimension(100, 50));
        lblBtnCardLayout1.setMinimumSize(new java.awt.Dimension(100, 50));
        lblBtnCardLayout1.setPreferredSize(new java.awt.Dimension(100, 50));
        add(lblBtnCardLayout1, java.awt.BorderLayout.CENTER);
        //this.lblImgFrameHeader.setLayout(new OverlayLayout(this.lblImgFrameHeader));
        this.lblImgFrameHeader.add(this.lblBtnCardLayout1);
        this.lblBtnCardLayout1.setBounds(
            500,
            120,
            100,
            80);
        //this.lblImgFrameHeader.getPreferredSize().width/2
        //- this.lblBtnCardLayout1.getPreferredSize().width,
        //this.lblImgFrameHeader.getPreferredSize().height
        //- this.lblBtnCardLayout1.getPreferredSize().height,

        lblImgFrameHeader.setBackground(new Color(0,0,0,0));
        lblImgFrameHeader.setForeground(new Color(0,0,0,255));
        lblImgFrameHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgFrameHeader.setIcon(new ImageIcon(ImageTool.getScaledImage("Home\\Component\\FrameHeader\\imgFrameHeader.png", 1200, 800)));
        lblImgFrameHeader.setText("jLabel1");
        lblImgFrameHeader.setMaximumSize(new java.awt.Dimension(1200, 200));
        lblImgFrameHeader.setMinimumSize(new java.awt.Dimension(1200, 200));
        lblImgFrameHeader.setOpaque(true);
        lblImgFrameHeader.setPreferredSize(new java.awt.Dimension(1200, 200));
        lblImgFrameHeader.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(lblImgFrameHeader, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBtnCardLayout1;
    private javax.swing.JLabel lblImgFrameHeader;
    // End of variables declaration//GEN-END:variables
}
